# Cristallographie: oxyde de magnésium

In [40]:
#importation du matériau
from pymatgen import MPRester
import numpy as np #Pour faire les vérifications
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer 

with MPRester("0GxLMrZ3A1RsWdHOh") as m:
    structure = m.get_structure_by_material_id("mp-1009129")
SgA= SpacegroupAnalyzer(structure)#Création d'un objet pour l'analyse de la structure
Lat=SgA.get_conventional_standard_structure() #Pour avoir la structure conventionnelle
Lattice=Lat.lattice

In [41]:
#Vecteurs du reseau direct
a,b,c = Lattice.matrix[:]
#Vecteurs du reseau reciproque
RLat= Lattice.reciprocal_lattice
RLat
h,k,l= RLat.matrix[:]
h,k,l
#Verification vecteurs du reseau direct et reciproque
import numpy as np
ah=np.dot(a,h)
bk=np.dot(b,k)
cl=np.dot(c,l)
#Type de maille
Tdm="conventionnelle" #Car demandé pour la structure
#Système Cristalline
SC=SgA.get_crystal_system()
#Groupe Ponctuel
GP= SgA.get_point_group_symbol()

In [42]:
#Cellule pour l'affichage
display(Lattice)
print("Les vecteurs de base pour le réseau direct sont:")
display(a,b,c)
print("Les vecteurs de base pour le réseau réciproque sont:")
display(h,k,l)
print("Pour vérifier que ces vecteurs sont corrects on peut multiplier les vecteurs du réseau direct par leur "
      "vecteur correspondant dans le réseau réciproque. On devrait obtenir 2pi.")
print("a * h = ",ah)
print("b * k = ",bk)
print("c * l = ",cl)
print("Le type de maille est :",Tdm,".") 
print("Le système cristallin est :",SC,". ")
print("On peut le voir dans l'objet Lattice ci-dessus: a=b≠c ,  gamma=120° et beta=alpha=90°")
print("Le groupe ponctuel est :",GP,".")

Lattice
    abc : 2.9385135137175356 2.9385135137175356 2.67989347
 angles : 90.0 90.0 120.00000000000001
 volume : 20.04026900088922
      A : 1.4692567568587678 -2.5448273522432583 0.0
      B : 1.4692567568587678 2.5448273522432583 0.0
      C : 0.0 0.0 2.67989347

Les vecteurs de base pour le réseau direct sont:


array([ 1.46925676, -2.54482735,  0.        ])

array([1.46925676, 2.54482735, 0.        ])

array([0.        , 0.        , 2.67989347])

Les vecteurs de base pour le réseau réciproque sont:


array([ 2.13821896, -1.23450129,  0.        ])

array([2.13821896, 1.23450129, 0.        ])

array([0.        , 0.        , 2.34456533])

Pour vérifier que ces vecteurs sont corrects on peut multiplier les vecteurs du réseau direct par leur vecteur correspondant dans le réseau réciproque. On devrait obtenir 2pi.
a * h =  6.283185307179586
b * k =  6.283185307179586
c * l =  6.283185307179585
Le type de maille est : conventionnelle .
Le système cristallin est : hexagonal . 
On peut le voir dans l'objet Lattice ci-dessus: a=b≠c ,  gamma=120° et beta=alpha=90°
Le groupe ponctuel est : -6m2 .
