In [107]:
from pymatgen import MPRester

with MPRester("0GxLMrZ3A1RsWdHOh") as m:
    # Structure for material id
    structure = m.get_structure_by_material_id("mp-1009129")
Lattice = structure.lattice 
Lattice

Lattice
    abc : 2.67989347 2.938513277414781 2.938532189392922
 angles : 120.00020225761145 90.0 90.0
 volume : 20.04035391084419
      A : 0.0 0.0 -2.67989347
      B : -1.46924742 -2.54483247 0.0
      C : -1.46926633 2.54484339 0.0

In [108]:
#Vecteurs du reseau direct
a,b,c = Lattice.matrix[:]
a,b,c

(array([ 0.        ,  0.        , -2.67989347]),
 array([-1.46924742, -2.54483247,  0.        ]),
 array([-1.46926633,  2.54484339,  0.        ]))

In [109]:
#Vecteurs du reseau reciproque
RLat= Lattice.reciprocal_lattice
RLat
h,k,l= RLat.matrix[:]
h,k,l
#Verification vecteurs du reseau direct et reciproque
import numpy as np
np.dot(c,l)/(2*np.pi)
#np.dot(a,k)
#np.dot(a,l)

1.0

In [110]:
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

SgA= SpacegroupAnalyzer(structure)

In [111]:
#Type de maille
Tdm=SgA.get_lattice_type()
Tdm

'hexagonal'

In [112]:
#Structure Cristalline
SC=SgA.get_crystal_system()
SC

'hexagonal'

In [113]:
#Groupe Ponctuel
GP= SgA.get_point_group_symbol()
GP

'-6m2'